import sys
from grammar_loader import load_grammar
from parser import CFGParser
from analyzer import (
    detect_ambiguity,
    detect_associativity,
    detect_precedence,
)

def test_string(parser, tokens):
    print("\nString:", " ".join(tokens))

    trees = parser.parse(tokens)

    print("Number of parse trees:", len(trees))

    if len(trees) == 0:
        print("String not generated by grammar")
        return

    if detect_ambiguity(trees):
        print("Conclusion: Grammar is ambiguous")
    else:
        print("Conclusion: Grammar is unambiguous")

    # Asociatividad (solo si aplica)
    if tokens.count("+") >= 2:
        assoc = detect_associativity(trees[0])
        print("Associativity:", assoc)

    # Precedencia (solo si aplica)
    if "+" in tokens and "*" in tokens:
        prec = detect_precedence(trees[0])
        print("Precedence:", prec)

    for i, tree in enumerate(trees):
        print(f"\nTree {i+1}")
        print(tree.pretty())


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 main.py entrada.txt")
        return

    grammar_file = sys.argv[1]
    grammar = load_grammar(grammar_file)

    print("Grammar Loaded:\n")
    print(grammar)

    parser = CFGParser(grammar, "E")

    # Cadenas de prueba
    test_string(parser, ["id", "+", "id", "+", "id"])
    test_string(parser, ["id", "+", "id", "*", "id"])
    test_string(parser, ["id", "*", "id", "+", "id"])


if __name__ == "__main__":
    main()
